/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Greet: typeof import('./components/Greet.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    Tiptap: typeof import('./components/Tiptap.vue')['default']
  }
}
