// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Greet: typeof import('./components/Greet.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    Tiptap: typeof import('./components/Tiptap.vue')['default']
  }
}
